name: Npm Publish

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/npm-publish.yml
  workflow_dispatch:

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-publish.yml@npm-publish-1.1.0
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    with:
      build-command: |
        npm run build

        git config --global user.name 'FreePhoenix888'
        git config --global user.email 'freephoenix888@gmail.com'

        git add ./src/package.ts
        if git diff --staged --quiet
        then
          echo "No changes to commit"
        else
          git commit -m 'Generate new package class'
          git push origin main
        fi
      test-command: "echo 'Tests are temporarily disabled'"
      should-generate-documentation: true
      generate-documentation-command: "npm run documentation:generate"
        
